[package]
name = "app"
version = "0.1.0"
description = "A Tauri App"
authors = [ "you" ]
license = ""
repository = ""
default-run = "app"
edition = "2018"
build = "src/build.rs"

[build-dependencies]
tauri-build = "1.0.0-beta-rc.1"

[dependencies]
anyhow = "1.0"
serde_json = "1.0"
serde_rusqlite = "0.26"
serde = { version = "1.0", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
rusqlite = { version = "0.24", features = [] }
refinery = { version = "0.5", features = ["rusqlite-bundled"] }

[dependencies.tauri]
git = "https://github.com/tauri-apps/tauri"
branch = "dev"

[features]
default = [ "custom-protocol" ]
custom-protocol = [ "tauri/custom-protocol" ]
