[package]
name = "app"
version = "0.1.0"
description = "A Tauri App"
authors = [ "you" ]
license = ""
repository = ""
default-run = "app"
edition = "2018"
build = "src/build.rs"

[build-dependencies]
tauri-build = { version = "1.0.0-rc.1", features = [] }

[dependencies]
anyhow = "1.0"
dirs = "4.0"
serde_json = "1.0"
serde_rusqlite = "0.29"
serde = { version = "1.0", features = [ "derive" ] }
chrono = { version = "0.4", features = [ "serde" ] }
refinery = { version = "0.8", features = [ "rusqlite-bundled" ] }
rusqlite = { version = "0.26", features = [ ] }
strum_macros = "0.23"

  [dependencies.tauri]
  version = "1.0.0-rc.1"
  features = ["api-all"]

[features]
default = [ "custom-protocol" ]
custom-protocol = [ "tauri/custom-protocol" ]
