[package]
name = "app"
version = "0.1.0"
description = "A Tauri App"
authors = [ "you" ]
license = ""
repository = ""
default-run = "app"
edition = "2018"
build = "src/build.rs"

[build-dependencies]
tauri-build = { version = "1.0.0-beta.4" }

[dependencies]
anyhow = "1.0"
dirs = "4.0"
serde_json = "1.0"
serde_rusqlite = "0.29"
serde = { version = "1.0", features = [ "derive" ] }
chrono = { version = "0.4", features = [ "serde" ] }
rusqlite = { version = "0.26", features = [ ] }
strum = "0.23"
strum_macros = "0.23"

  [dependencies.refinery]
  rev = "cfe9eb8439ec44a6da8cae41afb9007487ed0e08"
  git = "https://github.com/rust-db/refinery"
  features = [ "rusqlite-bundled" ]

  [dependencies.tauri]
  version = "1.0.0-beta.8"
  features = ["api-all"]

[features]
default = [ "custom-protocol" ]
custom-protocol = [ "tauri/custom-protocol" ]
