easy_admin:
    site_name: '🍎 Compotes 🍏'

    list:
        max_results: 100

    design:
        menu:
            - label: 'admin.menu.account_operations'
            - { icon: chart-bar, label: "admin.menu.analytics", route: analytics, default: true }
            - { icon: money-check, label: "admin.menu.operations", entity: Operation }
            - { icon: box-open, label: "admin.menu.triage", entity: Triage }
            - { icon: piggy-bank, label: "admin.menu.bank_accounts", entity: BankAccount }

            - label: 'admin.menu.tags'
            - { icon: ruler-vertical, label: "admin.menu.tag_rules", entity: TagRule }
            - { icon: tags, label: "admin.menu.tags", entity: Tag }

            - label: 'admin.menu.actions'
            - { icon: upload, label: "admin.menu.import_operations", route: import_operations }
            - { icon: sync, label: "admin.menu.sync_operations", route: sync_operations }

    entities:
        BankAccount:
            class: App\Entity\BankAccount
            label: Bank accounts
            controller: App\Admin\AdminBankAccountController
            list:
                actions:
                    - '-delete'
                fields:
                    - id
                    - name
                    - slug
                    - currency
            form:
                actions:
                    - '-delete'
                fields:
                    - name
                    - property: currency
                      type: currency

        TagRule:
            class: App\Entity\TagRule
            label: Tag rules
            controller: App\Admin\AdminTagRuleController
            list:
                fields:
                    - id
                    - matchingPattern
                    - property: isRegex
                      type: boolean
                    - property: tags
                      template: easy_admin/field_with_tags.html.twig
            form:
                fields:
                    - matchingPattern
                    - property: isRegex
                      type: checkbox
                    - property: tags
                      type_options:
                          by_reference: false

        Operation:
            class: App\Entity\Operation
            label: admin.operations.title
            controller: App\Admin\AdminOperationController
            list:
                actions:
                    - show
                    - '-new'
                    - '-delete'
                    - '-edit'
                filters:
                    - property: 'operationDate'
                      type: App\Form\Filter\OperationMonthFilterType
                    - tags
                    - bankAccount
                fields:
                    - property: id
                      label: 'admin.operations.fields.id'
                    - property: operationDate
                      label: 'admin.operations.fields.operationDate'
                    - property: bankAccount
                      label: 'admin.operations.fields.bankAccount'
                    - property: type
                      label: 'admin.operations.fields.type'
                    - property: details
                      label: 'admin.operations.fields.details'
                    - property: amount
                      label: 'admin.operations.fields.amount'
                      type: float
                    - property: tags
                      label: 'admin.operations.fields.tags'
                      template: easy_admin/field_with_tags.html.twig

        Triage:
            class: App\Entity\Operation
            label: admin.triage.title
            controller: App\Admin\AdminTriageController
            templates:
                list: easy_admin/Triage/list.html.twig
            list:
                actions:
                    - '-show'
                    - '-new'
                    - '-search'
                dql_filter: |
                    entity.state = 'pending_triage'
                fields:
                    - property: id
                      label: 'admin.operations.fields.id'
                    - property: operationDate
                      label: 'admin.operations.fields.operationDate'
                    - property: type
                      label: 'admin.operations.fields.type'
                    - property: details
                      label: 'admin.operations.fields.details'
                    - property: amount
                      label: 'admin.operations.fields.amount'
                      type: float
            edit:
                actions:
                    - '-delete'
                fields:
                    - operationDate
                    - type
                    - amount
                    - initialDetails
                    - details

        Tag:
            class: App\Entity\Tag
            label: Tags
            list:
                actions:
                    - 'show'
                    - '-delete'
                fields:
                    - id
                    - name
                    - parent
            form:
                actions:
                    - '-delete'
