easy_admin:
    site_name: '🍎 Compotes 🍏'

    list:
        max_results: 100

    design:
        menu:
            - { icon: chart-bar, label: "Analytics", route: analytics, default: true }
            - { icon: money-check, entity: Operation }

            - label: ''
            - { icon: ruler-vertical, entity: TagRule }
            - { icon: tags, entity: Tag }

            - label: ''
            - { icon: upload, label: "Import operations", route: import_operations }
            - { icon: sync, label: "Sync operations", route: apply_rules }

    entities:
        TagRule:
            class: App\Entity\TagRule
            label: Tag rules
            controller: App\Admin\AdminTagRuleController
            list:
                fields:
                    - id
                    - matchingPattern
                    - property: isRegex
                      type: boolean
                    - property: tags
                      template: easy_admin/field_with_tags.html.twig
            form:
                fields:
                    - matchingPattern
                    - property: isRegex
                      type: checkbox
                    - property: tags
                      type_options:
                          by_reference: false

        Operation:
            class: App\Entity\Operation
            label: Operations
            controller: App\Admin\AdminOperationController
            list:
                actions:
                    - show
                    - '-new'
                    - '-delete'
                    - '-edit'
                filters:
                    - property: 'operationDate'
                      type: App\Form\Filter\OperationMonthFilterType
                fields:
                    - id
                    - operationDate
                    - type
                    - details
                    - property: amount
                      type: float
                    - property: tags
                      template: easy_admin/field_with_tags.html.twig

        Tag:
            class: App\Entity\Tag
            label: Tags
            list:
                actions:
                    - 'show'
                    - '-delete'
                fields:
                    - id
                    - name
                    - parent

