easy_admin:
    list:
        max_results: 100

    entities:
        Operation:
            class: App\Entity\Operation
            list:
                fields:
                    - id
                    - operationDate
                    - type
                    - details
                    - property: amount
                      type: float
