easy_admin:
    list:
        max_results: 100

    entities:
        TagRule:
            class: App\Entity\TagRule
            list:
                fields:
                    - id
                    - matchingPattern
                    - property: isRegex
                      type: boolean
            form:
                fields:
                    - matchingPattern
                    - property: isRegex
                      type: checkbox
                    - property: tags
                      type: App\Form\Type\TagsInputType
                      type_options:
                          attr:
                              "data-toggle": tagsinput

        Operation:
            class: App\Entity\Operation
            list:
                actions:
                    - show
                filters:
                    - property: 'operationDate'
                      type: App\Form\Filter\OperationMonthFilterType
                fields:
                    - id
                    - operationDate
                    - type
                    - details
                    - property: amount
                      type: float

        Tag:
            class: App\Entity\Tag
