easy_admin:
    list:
        max_results: 100

    design:
        menu:
            - { icon: home, label: "Admin home", route: easyadmin }
            - { icon: sync, label: "Sync operations", route: apply_rules }

            - label: ''
            - { icon: ruler-vertical, entity: TagRule }
            - { icon: tags, entity: Tag }

            - label: ''
            - { icon: money-check, entity: Operation }

    entities:
        TagRule:
            class: App\Entity\TagRule
            label: Tag rules
            controller: App\Admin\AdminTagRuleController
            list:
                fields:
                    - id
                    - matchingPattern
                    - property: isRegex
                      type: boolean
            form:
                fields:
                    - matchingPattern
                    - property: isRegex
                      type: checkbox
                    - property: tags
                      type_options:
                          by_reference: false

        Operation:
            class: App\Entity\Operation
            label: Operations
            list:
                actions:
                    - show
                filters:
                    - property: 'operationDate'
                      type: App\Form\Filter\OperationMonthFilterType
                fields:
                    - id
                    - operationDate
                    - type
                    - details
                    - property: amount
                      type: float
                    - property: tags
                      template: easy_admin/field_tags.html.twig

        Tag:
            class: App\Entity\Tag
            label: Tags
