image:
  file: .gitpod.dockerfile
ports:
    - port: 8000
      onOpen: open-preview
tasks:
    - init: |
          symfony composer install
          symfony console doctrine:database:drop --no-interaction --if-exists --force
          symfony console doctrine:database:create --no-interaction --if-not-exists
          symfony console doctrine:migrations:migrate --no-interaction
          symfony console doctrine:fixtures:load --no-interaction --append
          symfony console operations:import --no-interaction
          symfony console operations:update-tags --no-interaction
      command: |
          symfony serve
