parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            string $bankSourcesDir: '%kernel.project_dir%/account_exports'

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        public: true
        autoconfigure: false
