name: Docker Push

on:
    push:
        branches:
            - master
            - docker
        tags:
            - '*'

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v1
              with:
                  fetch-depth: 1

            - name: Build & push base PHP image
              uses: opspresso/action-docker@master
              with:
                  args: --docker
              env:
                  USERNAME: ${{ secrets.DOCKER_USERNAME }}
                  PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
                  TAG_NAME: ${GITHUB_REF/#refs\/*\/}
                  IMAGE_NAME: "orbitale/compotes-php"

            # Wait until https://github.com/opspresso/action-docker/pull/6 is merged.
            #- name: Build & push Compotes image
            #  uses: opspresso/action-docker@master
            #  with:
            #      args: --docker
            #  env:
            #      USERNAME: ${{ secrets.DOCKER_USERNAME }}
            #      PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
            #      BUILD_PATH: "Dockerfile.standalone"
            #      TAG_NAME: "latest"
            #      IMAGE_NAME: "orbitale/compotes"
