name: Docker Image

on:
    push:
        branches:
            - main
            - docker
        tags:
            - '*'

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v1
              with:
                  fetch-depth: 1

            - name: Build & push base PHP image
              uses: opspresso/action-docker@master
              with:
                  args: --docker
              env:
                  USERNAME: ${{ secrets.DOCKER_USERNAME }}
                  PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
                  IMAGE_NAME: "orbitale/compotes-php"
                  LATEST: true

            # Wait until https://github.com/opspresso/action-docker/pull/6 is merged.
            - name: Build & push Compotes image
              uses: opspresso/action-docker@master
              with:
                  args: --docker
              env:
                  USERNAME: ${{ secrets.DOCKER_USERNAME }}
                  PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
                  DOCKERFILE: "Dockerfile.full"
                  IMAGE_NAME: "orbitale/compotes"
                  LATEST: true
