name: PHP

on: [push]

jobs:
    build:
        name: Compotes

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1

            - name: Setup PHP
              uses: shivammathur/setup-php@1.7.2
              with:
                  php-version: '7.4'
                  extensions: gd, zip

            - name: Validate composer.json and composer.lock
              run: composer validate

            - name: Install Symfony binary
              run: wget https://get.symfony.com/cli/installer -O - | bash

            - name: Get composer cache directory
              id: composer-cache
              run: echo "::set-output name=dir::$(composer config cache-files-dir)"

            - name: Cache composer dependencies
              uses: actions/cache@v1
              with:
                  path: ${{ steps.composer-cache.outputs.dir }}
                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                  restore-keys: ${{ runner.os }}-composer-

            - name: Install the project
              run: |
                  export PATH="$HOME/.symfony/bin:$PATH"
                  make install

            - name: '🚀 CS'
              run: |
                export PATH="$HOME/.symfony/bin:$PATH"
                make cs-dry

            - name: '🚀 Lint'
              run: |
                export PATH="$HOME/.symfony/bin:$PATH"
                make lint

            - name: Check composer dependencies for no security issue
              run: |
                export PATH="$HOME/.symfony/bin:$PATH"
                symfony security:check

            - name: Install PHPUnit
              run: |
                export PATH="$HOME/.symfony/bin:$PATH"
                make install-phpunit

            - name: '🚀 PHPStan'
              run: |
                export PATH="$HOME/.symfony/bin:$PATH"
                make phpstan

            - name: Setup the test database
              run: |
                export PATH="$HOME/.symfony/bin:$PATH"
                make test-db

            - name: '🚀 PHPUnit'
              run: |
                export PATH="$HOME/.symfony/bin:$PATH"
                make phpunit
