name: PHP

on: [push]

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1

            - name: Setup PHP
              uses: shivammathur/setup-php@1.7.2
              with:
                  php-version: '7.4'
                  extensions: gd, zip

            - name: Validate composer.json and composer.lock
              run: composer validate

            - name: Install dependencies
              run: composer install --prefer-dist --no-progress --no-suggest

            - name: PHPStan
              run: make phpstan

            - name: CS
              run: make cs-dry

            - name: Lint
              run: make lint
